name: fe-cex
recipe: drupal9
config:
  webroot: docroot
  composer_version: '2.1.8'
  php: '7.4'
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - npm install -g npm@7.21.0 gulp
    build:
      - composer install
tooling:
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
  npm:
    service: appserver
  gulp:
    service: appserver
